custom Polymorphic Lookup field/objects/PolymorphicLookupObject__mdt/PolymorphicLookupObject__mdt.object-meta.xml
<CustomObject>
    <description>PolymorphicLookupObject Custom Metadata records holds the sObjects and their details which are used to enable dynamic polymorphic Looup fields.</description>
    <label>Polymorphic Lookup Object</label>
    <pluralLabel>Polymorphic Lookup Objects</pluralLabel>
</CustomObject>

custom Polymorphic Lookup field/objects/PolymorphicLookupObject__mdt/fields/IsCreateNewRecordAllowed__c.field-meta.xml
<CustomField>
    <fullName>IsCreateNewRecordAllowed__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This is a boolean checkbox to allow or restrict creation of new records. Default is True means New Record is allowed to create.However even if this checkboc is true an duser doesnt have create permssion they will not be able to create New Records</description>
    <label>IsCreateNewRecordAllowed</label>
    <type>Checkbox</type>
</CustomField>

custom Polymorphic Lookup field/objects/PolymorphicLookupObject__mdt/fields/sObject_Display_IconName__c.field-meta.xml
<CustomField>
    <fullName>sObject_Display_IconName__c</fullName>
    <label>sObject Display IconName</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

custom Polymorphic Lookup field/objects/PolymorphicLookupObject__mdt/fields/sObjectAPIName__c.field-meta.xml
<CustomField>
    <fullName>sObjectAPIName__c</fullName>
    <description>This field holds the API Name of the sObject</description>
    <label>sObjectAPIName</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

custom Polymorphic Lookup field/objects/PolymorphicLookupObject__mdt/fields/sObjectLabel__c.field-meta.xml
<CustomField>
    <fullName>sObjectLabel__c</fullName>
    <description>This field holds the Label of sObject</description>
    <label>sObjectLabel</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

custom Polymorphic Lookup field/objects/PolymorphicLookupObject__mdt/fields/sObjectLookup_subtitle_field__c.field-meta.xml
<CustomField>
    <fullName>sObjectLookup_subtitle_field__c</fullName>
    <label>sObjectLookup Subtitle field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

custom Polymorphic Lookup field/objects/PolymorphicLookupObject__mdt/fields/sObjectPluralName__c.field-meta.xml
<CustomField>
    <fullName>sObjectPluralName__c</fullName>
    <description>This field holds the sObjects Plural Name</description>
    <label>sObjectPluralName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

custom Polymorphic Lookup field/objects/PolymorphicLookupObject__mdt/fields/sObjectRecords_Search_by_field__c.field-meta.xml
<CustomField>
    <fullName>sObjectRecords_Search_by_field__c</fullName>
    <label>sObjectRecords Search by field</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

custom Polymorphic Lookup field/classes/PolymorphicLookupObjects.cls
/****
    @description       :
    @author            : Amit Agarwal
    @group             :
    @last modified on  : 
    @last modified by  : Amit Agarwal
****/
public with sharing class PolymorphicLookupObjects {
    public PolymorphicLookupObjects() {

    }
    @AuraEnabled(cacheable=true)
    public static List<sObject> getObjectLookupList(){
        String Query = '';
        Query  = 'SELECT Id, IsCreateNewRecordAllowed__c,sObjectAPIName__c, sObjectLabel__c, sObjectPluralName__c, sObjectRecords_Search_by_field__c, sObjectLookup_subtitle_field__c, sObject_Display_IconName__c FROM PolymorphicLookupObject__mdt '; 
        List<SObject> sObjectList = Database.query(Query);
        return sObjectList;
    }
}